// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktgcackltnqqdalzfltx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0Z2NhY2tsdG5xcWRhbHpmbHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjg0NjQsImV4cCI6MjA2NTYwNDQ2NH0.VcT-BMtcPVGC6_OOznIRnMchusBzccVVZEbWJDNP8qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);